### ISSUE TITLE
Conditional Arg1 doesn't work

### ISSUE THREAD

**Issue by aktary** [aboutlo/ether-swr#1]
The way things are structured now, the [conditional execution built into SWR](https://swr.vercel.app/docs/conditional-fetching) doesn't work.  Passing a falsey value into Arg1 still results in execution.

**Comment by aboutlo** [comment]
Can you provide a minimal example of what you are trying to do?
Regardless, the package provides just a fetcher function for now. I believe the issue is directly in SWR.
