### ISSUE TITLE
Unauthenticated requests

### ISSUE THREAD

**Issue by beamercola** [aboutlo/ether-swr#13]
Is it possible to make a request to a contract without providing a signer?

For instance:

```
const { data: items } = useEtherSWR([
  contractAddress,
  "all",
])
```

I get `TypeError: Cannot read property 'getSigner' of undefined`

Thanks!

**Comment by aboutlo** [comment]
`ether-swr` is built with the idea of always having a signer available aka using `<Web3ReactProvider>`.  I don't see a problem to use `useEtherSWR([  0x0....1,  "all"])` with a signer. 
Please add more detail about your use case

**Comment by beamercola** [comment]
Ah I see, in my scenario I'm just looking to query some basic data out of a contract for listing available NFTs - the user isn't connecting their wallet until purchase.

**Comment by aboutlo** [comment]
I see, so it makes sense your use case. 

You can try to change the provider here
https://github.com/aboutlo/ether-swr/blob/master/examples/helloworld/src/App.tsx#L85 

You could use directly an ethers.js provider https://docs.ethers.io/v5/api/providers/#providers 

```
const provider = new JsonRpcProvider(
    'your URL with API key here '
  )
```

But I feel something need to be changed here https://github.com/aboutlo/ether-swr/blob/master/src/ether-js-fetcher.ts
and then add the tests here: https://github.com/aboutlo/ether-swr/blob/master/test/ether-js-fetcher.test.tsx

Can you open a PR to implement this?

**Comment by aboutlo** [comment]
hey @beamercola with ether-swr 2.0.1 you can pass a provider without the needs of having a signer
