### ISSUE TITLE
cache is not exported from swr

### ISSUE THREAD

**Issue by jakecza** [aboutlo/ether-swr#14]
failing to compile useEtherSWR.js (using swr v1.0.0)

![image](https://user-images.githubusercontent.com/36149387/131237526-82a1681b-b517-4414-b7c3-154c3e3438b5.png)

**Comment by aboutlo** [comment]
hey @jakecza this is an actual issue. 
They dropped SWR 1.0  
I will have a look but meanwhile, the last stable version is https://github.com/vercel/swr/releases/tag/0.5.6

**Comment by aboutlo** [comment]
here is how the cache is now handled: https://swr.vercel.app/docs/advanced/cache
