### ISSUE TITLE
Help : How do I connect to Infura/Alchemy using ether-swr?

### ISSUE THREAD

**Issue by pbshgthm** [aboutlo/ether-swr#20]
The given example shows ether-swr connected to injected connector. For functions like getLogs, I need to connect to an RPC provider. Is there something I could look up for the same? I've tried reading various articles/tutorials but I couldn't find anything that follows the same way ether-swr does. I'd like to get the address from MetaMask and make multiple getLog queries to the Alchemy. Pointing to the right resource is would be really helpful. Thanks!

**Comment by aboutlo** [comment]
Mmm not sure it can work. 

Never tried to use `getLogs` with ether-swr but you could use directly an ethers.js provider https://docs.ethers.io/v5/api/providers/#providers 

```
const web3Provider = new JsonRpcProvider(
    'your URL with API key here '
  )
```
then you pass the web3Provider to `EtherSWRConfig` or directly to `useEtherSWR`.

```
<EtherSWRConfig
          value={{
            web3Provider,
          }}
        >
          <DoSomethingWithTheLogs/>
</EtherSWRConfig>

function DoSomethingWithTheLogs() {
          const { data } = useEtherSWR(['getLogs'])
          return <div>Balance, {data}</div>
        }

```
It looks like the filters can be built using a positional approach 
https://github.com/ethers-io/ethers.js/issues/908#issuecomment-649297025

However, `ether-swr` doesn't cover this use case.  So you can call `getLogs` but you can't filter. You can use a useEffect and getLogs with your filter as a workaround

**Comment by pbshgthm** [comment]
Got it. Thank you for the explanation! I think I'll go with directly wrapping SWR over ethers.

**Comment by pbshgthm** [comment]
Solved :)
