### ISSUE TITLE
Testing documentation

### ISSUE THREAD

**Issue by luchux** [aboutlo/ether-swr#21]
Would be nice to have an example of testing for mocking up the contracts and the providers, or with the best practice a test of a component using useEtherSWR should use.

**Comment by aboutlo** [comment]
Good question, @luchux I don't have specific documentation about that but you can have a look at what I did to test my custom hooks (e.g. `balanceOf`) 
https://github.com/aboutlo/ether-swr/blob/master/test/useBalanceOf.test.tsx

Let me know what you think of my approach :)

**Comment by aboutlo** [comment]
Closing, for now
