### ISSUE TITLE
Interact with Ethereum methods (e.g. getBalance)

### ISSUE THREAD

**Issue by lidachao111222** [aboutlo/ether-swr#8]
Hi, Lorenzo. Sorry for disturbing you. 

I have one question about the Interact with Ethereum methods when I use the getBalance function with ether-swr.
When I tried the minimal example. I saw that the ethereum amount won't change if I switch to another network(ex: from Ropsten to Rinkeby).  

Would you like to give me some ideas please? Thank you.

**Comment by aboutlo** [comment]
I haven't tested the minimal example with network switch but I can imagine two things:
- It will updated after 30'' (refreshInterval)  https://github.com/aboutlo/ether-swr/blob/master/examples/helloworld/src/App.tsx#L223
- You need to clear the SWR cache to make it happens immediately 

```
import cache from 'swr' 
cache.clear()
```

**Comment by lidachao111222** [comment]
Thanks for your reply. 

The first idea that I tried before. It doesn't work.  

I use the second idea like this:
`  useEffect(() => {
    if (library !== undefined) {
      cache.clear()
    }
  }, [chainId]);`

It also doesn't work.

The final solution is I used the idea you wrote "How to Fetch and Update Data From Ethereum with React and SWR".
It works! lol  
Here is the  code:


 useEffect(() => {
    if (library !== undefined) {
      // listen for changes on an Ethereum address
      console.log("listening for blocks...");
      library.on("block", () => {
        console.log("update eth balance...");
        mutate(undefined, true);
      });
      // remove listener when the component is unmounted
      return () => {
        library.removeAllListeners("block");
      };
    }
    // trigger the effect only on component mount
  }, [chainId]);


I am still trying to get balance by ether-swr.

**Comment by aboutlo** [comment]
Have a look at how it works https://github.com/NoahZinsmeister/web3-react.
The problem you are facing seems more related to the web3 provider than ether-swr itself.
